const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Turret,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.shadowlight,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.shadowlight.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame
	];
};
self.C3_JsPropNameTable = [
	{Flash: 0},
	{"1v1text": 0},
	{"1v1text2": 0},
	{"1v1text3": 0},
	{"1v1text4": 0},
	{"1v1text5": 0},
	{"1v1text6": 0},
	{"1v1text7": 0},
	{"1v1text8": 0},
	{AreaControlText: 0},
	{BombBackButton: 0},
	{BombBackButton2: 0},
	{BombBackButton3: 0},
	{BombBackButton4: 0},
	{BombBackButton5: 0},
	{BombBackButton6: 0},
	{BombGameText: 0},
	{BombLoadoutSelect: 0},
	{BombMap1: 0},
	{BombMap2: 0},
	{BombMap3: 0},
	{BombMapSelect: 0},
	{BombMapSelect2: 0},
	{BombMissionComplet: 0},
	{BombSpawn1: 0},
	{BombSpawn2: 0},
	{BombSpawn3: 0},
	{BombSpawn4: 0},
	{BombSpawn5: 0},
	{BombSpawn6: 0},
	{BombSpawn7: 0},
	{BombSpawn8: 0},
	{BombSpawn9: 0},
	{BombStartButton: 0},
	{BombStartButton2: 0},
	{BombStartButton3: 0},
	{BreifingMover: 0},
	{BriefingStarttext: 0},
	{Commendations: 0},
	{Commendations2: 0},
	{Commendations3: 0},
	{Commendations4: 0},
	{Commendations5: 0},
	{Controls: 0},
	{Credits: 0},
	{CreditsBackButton: 0},
	{Creditstext: 0},
	{DamageOutput1: 0},
	{DamageOutput2: 0},
	{DamageOutput3: 0},
	{DeathMatchGameText: 0},
	{DisclaimerText: 0},
	{FinalScoreBomb: 0},
	{Gamemodetext: 0},
	{HealthRemainingBomb: 0},
	{HostageGameText: 0},
	{HUDAssult: 0},
	{HUDAK: 0},
	{HUDAX50: 0},
	{HUDAX: 0},
	{HUDBreach: 0},
	{HUDBreachGun: 0},
	{HUDC4: 0},
	{HUDC4Bomb: 0},
	{HUDPistol: 0},
	{HUDColt: 0},
	{HUDHandgun: 0},
	{HUDDeagle: 0},
	{PlayerDeaths: 0},
	{HUDDeathsText: 0},
	{HUDGADrone: 0},
	{HUDDrone: 0},
	{HUDRifle: 0},
	{HUDEBR: 0},
	{HUDEMPLauncher: 0},
	{HUDEMPLaunch: 0},
	{HUDEMP: 0},
	{HUDEMPNade: 0},
	{HUDFrags: 0},
	{HUDFragNades: 0},
	{HUDGAC22: 0},
	{HUDGAR10: 0},
	{HUDGAREVMkV: 0},
	{HUDGASMG20: 0},
	{HUDGATypeXV: 0},
	{HUDGAVolt10: 0},
	{PlayerHPHUD: 0},
	{HUDHPText: 0},
	{HUDImpact: 0},
	{HUDImpactGrenade: 0},
	{HUDLMGTurretPlacement: 0},
	{HUDLMGturret: 0},
	{HUDLMGTurretAmmo: 0},
	{HUDLMGturret2: 0},
	{HUDSMG: 0},
	{HUDMAC: 0},
	{HUDSlug: 0},
	{HUDMKA: 0},
	{HUDMossberg: 0},
	{HUDMoss: 0},
	{HUDMP5: 0},
	{HUDPBPWall: 0},
	{HUDPBPW: 0},
	{HUDScore: 0},
	{HUDShotgun: 0},
	{HUDShorty: 0},
	{HUDSmoke: 0},
	{HUDSmokeGrenade: 0},
	{HUDStim: 0},
	{HUDStimPistol: 0},
	{HUDToxic: 0},
	{HUDToxicGrenade: 0},
	{InventoryBackButton: 0},
	{InventoryButton: 0},
	{Lines: 0},
	{MoneyDisplay: 0},
	{Notes2: 0},
	{Payout: 0},
	{ReloadsRemaining: 0},
	{ReloadHUD2: 0},
	{ReloadsHUD: 0},
	{SettingsText: 0},
	{ShopBackButton: 0},
	{StartCampaignSaveText: 0},
	{StartCampaignText: 0},
	{StartGame: 0},
	{TeamCredits: 0},
	{Text: 0},
	{Text2: 0},
	{TrainingBackButton: 0},
	{TrainingControlsButton: 0},
	{TrainingLoadoutButton: 0},
	{TrainingRoomBackButton: 0},
	{TrainingRoomText: 0},
	{VulpinesNotebookText: 0},
	{WeaponBuyerText: 0},
	{WeaponBuyerText10: 0},
	{WeaponBuyerText11: 0},
	{WeaponBuyerText12: 0},
	{WeaponBuyerText13: 0},
	{WeaponBuyerText14: 0},
	{WeaponBuyerText15: 0},
	{WeaponBuyerText16: 0},
	{WeaponBuyerText17: 0},
	{WeaponBuyerText18: 0},
	{WeaponBuyerText19: 0},
	{WeaponBuyerText2: 0},
	{WeaponBuyerText20: 0},
	{WeaponBuyerText21: 0},
	{WeaponBuyerText22: 0},
	{WeaponBuyerText23: 0},
	{WeaponBuyerText24: 0},
	{WeaponBuyerText25: 0},
	{WeaponBuyerText26: 0},
	{WeaponBuyerText27: 0},
	{WeaponBuyerText28: 0},
	{WeaponBuyerText29: 0},
	{WeaponBuyerText3: 0},
	{WeaponBuyerText30: 0},
	{WeaponBuyerText31: 0},
	{WeaponBuyerText32: 0},
	{WeaponBuyerText33: 0},
	{WeaponBuyerText34: 0},
	{WeaponBuyerText35: 0},
	{WeaponBuyerText36: 0},
	{WeaponBuyerText37: 0},
	{WeaponBuyerText38: 0},
	{WeaponBuyerText39: 0},
	{WeaponBuyerText4: 0},
	{WeaponBuyerText40: 0},
	{WeaponBuyerText41: 0},
	{WeaponBuyerText5: 0},
	{WeaponBuyerText6: 0},
	{WeaponBuyerText7: 0},
	{WeaponBuyerText8: 0},
	{WeaponBuyerText9: 0},
	{WeaponIndicator1: 0},
	{WeaponIndicator2: 0},
	{WeaponIndicator3: 0},
	{WeaponIndicator4: 0},
	{WeaponSelectAK: 0},
	{WeaponSelectAX: 0},
	{WeaponSelectBreach: 0},
	{WeaponSelectC4: 0},
	{WeaponSelectColt: 0},
	{WeaponSelectDeagle: 0},
	{WeaponSelectEBR: 0},
	{WeaponSelectEMP: 0},
	{WeaponSelectEMPLaunch: 0},
	{WeaponSelectFrags: 0},
	{WeaponSelectGAAssault: 0},
	{WeaponSelectGADrone: 0},
	{WeaponSelectGAHandgun: 0},
	{WeaponSelectGAMarksman: 0},
	{WeaponSelectGAShotgun: 0},
	{WeaponSelectGASMG: 0},
	{WeaponSelectGASniper: 0},
	{WeaponSelectImpact: 0},
	{WeaponSelectMAC: 0},
	{WeaponSelectMKA: 0},
	{WeaponSelectMoss: 0},
	{WeaponSelectMP5: 0},
	{WeaponSelectNonePrimary: 0},
	{WeaponSelectNonePrime: 0},
	{WeaponSelectNoneSec: 0},
	{WeaponSelectNoneSecondary: 0},
	{WeaponSelectRandomPrimary: 0},
	{WeaponSelectRandomPrime: 0},
	{WeaponSelectRandomSec: 0},
	{WeaponSelectRandomSecondary2: 0},
	{WeaponSelectShorty: 0},
	{WeaponSelectSmoke: 0},
	{WeaponSelectStim: 0},
	{WeaponSelectToxic: 0},
	{WeaponSelectTurret: 0},
	{WeaponSelectWall: 0},
	{WeaponShopText: 0},
	{ShopText: 0},
	{ShopText2: 0},
	{WeaponBuyerText42: 0},
	{WeaponBuyerText43: 0},
	{Solid: 0},
	{AltCollison: 0},
	{AltCollison2: 0},
	{AltCollison3: 0},
	{AltCollison4: 0},
	{AltCollison5: 0},
	{ShadowCaster: 0},
	{Collisions: 0},
	{Bullet: 0},
	{AK47Bullet: 0},
	{AX50Bullet: 0},
	{BreachingGunBullet: 0},
	{C4: 0},
	{ScrollTo: 0},
	{Crosshair: 0},
	{DeagleBullet: 0},
	{Diffuser: 0},
	{DisplayBullet: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Drone: 0},
	{EMPBullet: 0},
	{EMPBurst: 0},
	{EMPBurst2: 0},
	{EMPGrenade: 0},
	{Explosion: 0},
	{Explosion2: 0},
	{FragGrenade: 0},
	{GAC22Bullet: 0},
	{GAR10Bullet: 0},
	{GAREVMkVBullet: 0},
	{GASMG20Bullet: 0},
	{GATypeXVBullet: 0},
	{GAVolt10: 0},
	{ImpactGrenade: 0},
	{Knife: 0},
	{LMGBullet: 0},
	{LMGTurret: 0},
	{MAC11Bullet: 0},
	{Mk14EBRBullet: 0},
	{MKA1919Shell: 0},
	{MossbergShell: 0},
	{MP5Bullet: 0},
	{WallHP: 0},
	{PBPW: 0},
	{PistolBullet: 0},
	{HP: 0},
	{ReloadsPrime: 0},
	{ReloadsSecondary: 0},
	{AssultAmmo: 0},
	{PrimeSMGAmmo: 0},
	{MarksmanAmmo: 0},
	{PrimeShotgunAmmo: 0},
	{SlugShotgunAmmo: 0},
	{SniperAmmo: 0},
	{SecShotgunAmmo: 0},
	{SecSMGAmmo: 0},
	{HandgunAmmo: 0},
	{Handgun2Ammo: 0},
	{BreachCannonAmmo: 0},
	{StimDartAmmo: 0},
	{EMPLauncherAmmo: 0},
	{SecEMPGrenades: 0},
	{FragGrenades: 0},
	{C4Charges: 0},
	{GAAssaultAmmo: 0},
	{GASMGAmmo: 0},
	{GAMarksmanAmmo: 0},
	{GASniperAmmo: 0},
	{GAHandgunAmmo: 0},
	{GAShotgunAmmo: 0},
	{LMGTurretPlacement: 0},
	{LMGTurretAmmo: 0},
	{GADroneUses: 0},
	{BPWallPlacements: 0},
	{SmokeGrenades: 0},
	{ImpactGrenades: 0},
	{ToxicGrenades: 0},
	{Deaths: 0},
	{Turret: 0},
	{Pin: 0},
	{Player: 0},
	{ShortyShell: 0},
	{Timer: 0},
	{Smoke: 0},
	{SmokeGrenade: 0},
	{ToxicGrenade: 0},
	{ToxicSmoke: 0},
	{ShadowLight: 0},
	{BanditCharge: 0},
	{BanditCharge2: 0},
	{BanditCharge3: 0},
	{BarbedWire: 0},
	{Bomb: 0},
	{Bomb2: 0},
	{Box: 0},
	{ControlArea: 0},
	{Crate: 0},
	{DamageReset: 0},
	{DisplayEMP: 0},
	{DisplayDiffuser: 0},
	{Damage: 0},
	{Dummy1: 0},
	{Dummy2: 0},
	{Dummy3: 0},
	{ElectifiedBarbedWire: 0},
	{ElectifiedBarbedWire2: 0},
	{EMPdBandit: 0},
	{EMPdBandit2: 0},
	{EMPdBandit3: 0},
	{HorizontalBarricadedDoor: 0},
	{HorzElectricalHazard: 0},
	{HorzElectricalHazard2: 0},
	{HorzElectricalHazard3: 0},
	{Hostage: 0},
	{LargeCrate: 0},
	{SoftWall: 0},
	{Table: 0},
	{VertElectricalHazard: 0},
	{VertElectricalHazard2: 0},
	{VertElectricalHazard3: 0},
	{VerticalBarricadeDoor: 0},
	{Audio: 0},
	{Keyboard: 0},
	{LOGO: 0},
	{Mouse: 0},
	{ScrollWheel: 0},
	{DockFloor: 0},
	{HorizontalBarracadedDoorIndicator: 0},
	{SoftWallIndicator: 0},
	{SpawnPoint: 0},
	{SpawnPoints2: 0},
	{SpawnPoints3: 0},
	{StoneFloor: 0},
	{StoneFloor10: 0},
	{StoneFloor11: 0},
	{StoneFloor12: 0},
	{StoneFloor13: 0},
	{StoneFloor14: 0},
	{StoneFloor15: 0},
	{StoneFloor16: 0},
	{StoneFloor17: 0},
	{StoneFloor2: 0},
	{StoneFloor3: 0},
	{StoneFloor4: 0},
	{StoneFloor5: 0},
	{StoneFloor6: 0},
	{StoneFloor7: 0},
	{StoneFloor8: 0},
	{StoneFloor9: 0},
	{TrainingRoomBackground: 0},
	{VerticalBarricadeDoorIndicatior: 0},
	{Water: 0},
	{WoodFloor2: 0},
	{HUDAmmoBox: 0},
	{HUDAmmoBox2: 0},
	{HUDAmmoBox3: 0},
	{HUDBreachingGunBullet: 0},
	{HUDBullet: 0},
	{HUDBullet2: 0},
	{HUDDroneDisplay: 0},
	{HUDEMPGrenade: 0},
	{HUDGrenade: 0},
	{HUDHPIndicator: 0},
	{HUDImpactnade: 0},
	{HUDLMGBullet: 0},
	{HUDPBPWDisplay: 0},
	{HUDShotgunBullet: 0},
	{HUDShotgunBullet2: 0},
	{HUDSmokeNade: 0},
	{HUDToxicNade: 0},
	{Important: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{Enemy: 0},
	{EnemyBullet: 0},
	{EnemyBullet1: 0},
	{Computer: 0},
	{Background: 0},
	{ArrowLeft: 0},
	{ArrowRight: 0},
	{Background2: 0},
	{ComputerPorts: 0},
	{ComputerObject: 0},
	{ComputerObject2: 0},
	{ComputerObject3: 0},
	{ComputerButton: 0},
	{PortBlocker1: 0},
	{PortBlockerText1: 0},
	{PortBlockerText2: 0},
	{PortBlockerText3: 0},
	{PortBlocker2: 0},
	{PortBlocker3: 0},
	{ArrowLeft2: 0},
	{ArrowLeft3: 0},
	{ArrowLeft4: 0},
	{ArrowLeft5: 0},
	{ArrowLeft6: 0},
	{ArrowRight2: 0},
	{ArrowRight3: 0},
	{ArrowRight4: 0},
	{ArrowRight5: 0},
	{ArrowRight6: 0},
	{MoneyDisplayBackground: 0},
	{TestFireBonus: 0},
	{TestFireBonus2: 0},
	{TestFireBonus3: 0},
	{RelevantCollisions: 0},
	{Projectiles: 0},
	{Electrical: 0},
	{EMPD: 0},
	{Ebarbed: 0},
	{PlayerBullets: 0},
	{TestFireBonusClaimed: 0},
	{TestFireBonusClaimed2: 0},
	{WHITEWAVEUSB: 0},
	{Port1Unlocked: 0},
	{Score: 0},
	{Money: 0},
	{EnemyKills: 0},
	{MissionsCompleted: 0},
	{MissionsFailed: 0},
	{Collectables: 0},
	{EnemyKillNumber: 0},
	{Gear: 0},
	{AK47Bought: 0},
	{MP5Bought: 0},
	{Mk14EBRBought: 0},
	{MossbergBought: 0},
	{MKABought: 0},
	{AX50Bought: 0},
	{GAR10Bought: 0},
	{GASMG20Bought: 0},
	{GAEVRMkVBought: 0},
	{GATypeXVBought: 0},
	{ColtM1911Bought: 0},
	{ShortyBought: 0},
	{DeagleBought: 0},
	{MAC11Bought: 0},
	{GAC22Bought: 0},
	{GAVolt10Bought: 0},
	{BreachingCannonBought: 0},
	{EMPLauncherBought: 0},
	{StimDartsBought: 0},
	{GAEDMkIIIBought: 0},
	{LMGTurretBought: 0},
	{PortableBPWallBought: 0},
	{FragGrenadeBought: 0},
	{C4ExplosiveBought: 0},
	{EMPGrenadeBought: 0},
	{SmokeGrenadeBought: 0},
	{ToxicGrenadeBought: 0},
	{GATIGrenadeBought: 0},
	{PlayerDetection: 0},
	{PlayerHealth: 0},
	{Spawn1: 0},
	{Spawn2: 0},
	{Spawn3: 0},
	{BombDefuse1: 0},
	{BombDefuse2: 0},
	{Assult: 0},
	{PrimeShot: 0},
	{Rifle: 0},
	{PrimeSMG: 0},
	{SlugShot: 0},
	{Sniper: 0},
	{Shotgun: 0},
	{Handgun: 0},
	{Pistol: 0},
	{SMG: 0},
	{BreachingGun: 0},
	{Stim: 0},
	{PrimeEMP: 0},
	{EMPGrenades: 0},
	{C4Priming: 0},
	{GAAssault: 0},
	{GASMG: 0},
	{GAMarksman: 0},
	{GASniper: 0},
	{GAHandgun: 0},
	{GAShotgun: 0},
	{LMGTurretPriming: 0},
	{GADrone: 0},
	{DroneSpawned: 0},
	{BPWall: 0}
];

self.InstanceType = {
	_1v1text: class extends self.ITextInstance {},
	_1v1text2: class extends self.ITextInstance {},
	_1v1text3: class extends self.ITextInstance {},
	_1v1text4: class extends self.ITextInstance {},
	_1v1text5: class extends self.ITextInstance {},
	_1v1text6: class extends self.ITextInstance {},
	_1v1text7: class extends self.ITextInstance {},
	_1v1text8: class extends self.ITextInstance {},
	AreaControlText: class extends self.ITextInstance {},
	BombBackButton: class extends self.ITextInstance {},
	BombBackButton2: class extends self.ITextInstance {},
	BombBackButton3: class extends self.ITextInstance {},
	BombBackButton4: class extends self.ITextInstance {},
	BombBackButton5: class extends self.ITextInstance {},
	BombBackButton6: class extends self.ITextInstance {},
	BombGameText: class extends self.ITextInstance {},
	BombLoadoutSelect: class extends self.ITextInstance {},
	BombMap1: class extends self.ITextInstance {},
	BombMap2: class extends self.ITextInstance {},
	BombMap3: class extends self.ITextInstance {},
	BombMapSelect: class extends self.ITextInstance {},
	BombMapSelect2: class extends self.ITextInstance {},
	BombMissionComplet: class extends self.ITextInstance {},
	BombSpawn1: class extends self.ITextInstance {},
	BombSpawn2: class extends self.ITextInstance {},
	BombSpawn3: class extends self.ITextInstance {},
	BombSpawn4: class extends self.ITextInstance {},
	BombSpawn5: class extends self.ITextInstance {},
	BombSpawn6: class extends self.ITextInstance {},
	BombSpawn7: class extends self.ITextInstance {},
	BombSpawn8: class extends self.ITextInstance {},
	BombSpawn9: class extends self.ITextInstance {},
	BombStartButton: class extends self.ITextInstance {},
	BombStartButton2: class extends self.ITextInstance {},
	BombStartButton3: class extends self.ITextInstance {},
	BreifingMover: class extends self.ITextInstance {},
	BriefingStarttext: class extends self.ITextInstance {},
	Commendations: class extends self.ITextInstance {},
	Commendations2: class extends self.ITextInstance {},
	Commendations3: class extends self.ITextInstance {},
	Commendations4: class extends self.ITextInstance {},
	Commendations5: class extends self.ITextInstance {},
	Controls: class extends self.ITextInstance {},
	Credits: class extends self.ITextInstance {},
	CreditsBackButton: class extends self.ITextInstance {},
	Creditstext: class extends self.ITextInstance {},
	DamageOutput1: class extends self.ITextInstance {},
	DamageOutput2: class extends self.ITextInstance {},
	DamageOutput3: class extends self.ITextInstance {},
	DeathMatchGameText: class extends self.ITextInstance {},
	DisclaimerText: class extends self.ITextInstance {},
	FinalScoreBomb: class extends self.ITextInstance {},
	Gamemodetext: class extends self.ITextInstance {},
	HealthRemainingBomb: class extends self.ITextInstance {},
	HostageGameText: class extends self.ITextInstance {},
	HUDAK: class extends self.ITextInstance {},
	HUDAX: class extends self.ITextInstance {},
	HUDBreachGun: class extends self.ITextInstance {},
	HUDC4Bomb: class extends self.ITextInstance {},
	HUDColt: class extends self.ITextInstance {},
	HUDDeagle: class extends self.ITextInstance {},
	HUDDeathsText: class extends self.ITextInstance {},
	HUDDrone: class extends self.ITextInstance {},
	HUDEBR: class extends self.ITextInstance {},
	HUDEMPLaunch: class extends self.ITextInstance {},
	HUDEMPNade: class extends self.ITextInstance {},
	HUDFragNades: class extends self.ITextInstance {},
	HUDGAC22: class extends self.ITextInstance {},
	HUDGAR10: class extends self.ITextInstance {},
	HUDGAREVMkV: class extends self.ITextInstance {},
	HUDGASMG20: class extends self.ITextInstance {},
	HUDGATypeXV: class extends self.ITextInstance {},
	HUDGAVolt10: class extends self.ITextInstance {},
	HUDHPText: class extends self.ITextInstance {},
	HUDImpactGrenade: class extends self.ITextInstance {},
	HUDLMGturret: class extends self.ITextInstance {},
	HUDLMGturret2: class extends self.ITextInstance {},
	HUDMAC: class extends self.ITextInstance {},
	HUDMKA: class extends self.ITextInstance {},
	HUDMoss: class extends self.ITextInstance {},
	HUDMP5: class extends self.ITextInstance {},
	HUDPBPW: class extends self.ITextInstance {},
	HUDScore: class extends self.ITextInstance {},
	HUDShorty: class extends self.ITextInstance {},
	HUDSmokeGrenade: class extends self.ITextInstance {},
	HUDStimPistol: class extends self.ITextInstance {},
	HUDToxicGrenade: class extends self.ITextInstance {},
	InventoryBackButton: class extends self.ITextInstance {},
	InventoryButton: class extends self.ITextInstance {},
	Lines: class extends self.ITextInstance {},
	MoneyDisplay: class extends self.ITextInstance {},
	Notes2: class extends self.ITextInstance {},
	Payout: class extends self.ITextInstance {},
	ReloadHUD2: class extends self.ITextInstance {},
	ReloadsHUD: class extends self.ITextInstance {},
	SettingsText: class extends self.ITextInstance {},
	ShopBackButton: class extends self.ITextInstance {},
	StartCampaignSaveText: class extends self.ITextInstance {},
	StartCampaignText: class extends self.ITextInstance {},
	StartGame: class extends self.ITextInstance {},
	TeamCredits: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	TrainingBackButton: class extends self.ITextInstance {},
	TrainingControlsButton: class extends self.ITextInstance {},
	TrainingLoadoutButton: class extends self.ITextInstance {},
	TrainingRoomBackButton: class extends self.ITextInstance {},
	TrainingRoomText: class extends self.ITextInstance {},
	VulpinesNotebookText: class extends self.ITextInstance {},
	WeaponBuyerText: class extends self.ITextInstance {},
	WeaponBuyerText10: class extends self.ITextInstance {},
	WeaponBuyerText11: class extends self.ITextInstance {},
	WeaponBuyerText12: class extends self.ITextInstance {},
	WeaponBuyerText13: class extends self.ITextInstance {},
	WeaponBuyerText14: class extends self.ITextInstance {},
	WeaponBuyerText15: class extends self.ITextInstance {},
	WeaponBuyerText16: class extends self.ITextInstance {},
	WeaponBuyerText17: class extends self.ITextInstance {},
	WeaponBuyerText18: class extends self.ITextInstance {},
	WeaponBuyerText19: class extends self.ITextInstance {},
	WeaponBuyerText2: class extends self.ITextInstance {},
	WeaponBuyerText20: class extends self.ITextInstance {},
	WeaponBuyerText21: class extends self.ITextInstance {},
	WeaponBuyerText22: class extends self.ITextInstance {},
	WeaponBuyerText23: class extends self.ITextInstance {},
	WeaponBuyerText24: class extends self.ITextInstance {},
	WeaponBuyerText25: class extends self.ITextInstance {},
	WeaponBuyerText26: class extends self.ITextInstance {},
	WeaponBuyerText27: class extends self.ITextInstance {},
	WeaponBuyerText28: class extends self.ITextInstance {},
	WeaponBuyerText29: class extends self.ITextInstance {},
	WeaponBuyerText3: class extends self.ITextInstance {},
	WeaponBuyerText30: class extends self.ITextInstance {},
	WeaponBuyerText31: class extends self.ITextInstance {},
	WeaponBuyerText32: class extends self.ITextInstance {},
	WeaponBuyerText33: class extends self.ITextInstance {},
	WeaponBuyerText34: class extends self.ITextInstance {},
	WeaponBuyerText35: class extends self.ITextInstance {},
	WeaponBuyerText36: class extends self.ITextInstance {},
	WeaponBuyerText37: class extends self.ITextInstance {},
	WeaponBuyerText38: class extends self.ITextInstance {},
	WeaponBuyerText39: class extends self.ITextInstance {},
	WeaponBuyerText4: class extends self.ITextInstance {},
	WeaponBuyerText40: class extends self.ITextInstance {},
	WeaponBuyerText41: class extends self.ITextInstance {},
	WeaponBuyerText5: class extends self.ITextInstance {},
	WeaponBuyerText6: class extends self.ITextInstance {},
	WeaponBuyerText7: class extends self.ITextInstance {},
	WeaponBuyerText8: class extends self.ITextInstance {},
	WeaponBuyerText9: class extends self.ITextInstance {},
	WeaponIndicator1: class extends self.ITextInstance {},
	WeaponIndicator2: class extends self.ITextInstance {},
	WeaponIndicator3: class extends self.ITextInstance {},
	WeaponIndicator4: class extends self.ITextInstance {},
	WeaponSelectAK: class extends self.ITextInstance {},
	WeaponSelectAX: class extends self.ITextInstance {},
	WeaponSelectBreach: class extends self.ITextInstance {},
	WeaponSelectC4: class extends self.ITextInstance {},
	WeaponSelectColt: class extends self.ITextInstance {},
	WeaponSelectDeagle: class extends self.ITextInstance {},
	WeaponSelectEBR: class extends self.ITextInstance {},
	WeaponSelectEMP: class extends self.ITextInstance {},
	WeaponSelectEMPLaunch: class extends self.ITextInstance {},
	WeaponSelectFrags: class extends self.ITextInstance {},
	WeaponSelectGAAssault: class extends self.ITextInstance {},
	WeaponSelectGADrone: class extends self.ITextInstance {},
	WeaponSelectGAHandgun: class extends self.ITextInstance {},
	WeaponSelectGAMarksman: class extends self.ITextInstance {},
	WeaponSelectGAShotgun: class extends self.ITextInstance {},
	WeaponSelectGASMG: class extends self.ITextInstance {},
	WeaponSelectGASniper: class extends self.ITextInstance {},
	WeaponSelectImpact: class extends self.ITextInstance {},
	WeaponSelectMAC: class extends self.ITextInstance {},
	WeaponSelectMKA: class extends self.ITextInstance {},
	WeaponSelectMoss: class extends self.ITextInstance {},
	WeaponSelectMP5: class extends self.ITextInstance {},
	WeaponSelectNonePrimary: class extends self.ITextInstance {},
	WeaponSelectNonePrime: class extends self.ITextInstance {},
	WeaponSelectNoneSec: class extends self.ITextInstance {},
	WeaponSelectNoneSecondary: class extends self.ITextInstance {},
	WeaponSelectRandomPrimary: class extends self.ITextInstance {},
	WeaponSelectRandomPrime: class extends self.ITextInstance {},
	WeaponSelectRandomSec: class extends self.ITextInstance {},
	WeaponSelectRandomSecondary2: class extends self.ITextInstance {},
	WeaponSelectShorty: class extends self.ITextInstance {},
	WeaponSelectSmoke: class extends self.ITextInstance {},
	WeaponSelectStim: class extends self.ITextInstance {},
	WeaponSelectToxic: class extends self.ITextInstance {},
	WeaponSelectTurret: class extends self.ITextInstance {},
	WeaponSelectWall: class extends self.ITextInstance {},
	WeaponShopText: class extends self.ITextInstance {},
	ShopText: class extends self.ITextInstance {},
	ShopText2: class extends self.ITextInstance {},
	WeaponBuyerText42: class extends self.ITextInstance {},
	WeaponBuyerText43: class extends self.ITextInstance {},
	AltCollison: class extends self.ISpriteInstance {},
	AltCollison2: class extends self.ISpriteInstance {},
	AltCollison3: class extends self.ISpriteInstance {},
	AltCollison4: class extends self.ISpriteInstance {},
	AltCollison5: class extends self.ISpriteInstance {},
	Collisions: class extends self.ISpriteInstance {},
	AK47Bullet: class extends self.ISpriteInstance {},
	AX50Bullet: class extends self.ISpriteInstance {},
	BreachingGunBullet: class extends self.ISpriteInstance {},
	C4: class extends self.ISpriteInstance {},
	Crosshair: class extends self.ISpriteInstance {},
	DeagleBullet: class extends self.ISpriteInstance {},
	Diffuser: class extends self.ISpriteInstance {},
	DisplayBullet: class extends self.ISpriteInstance {},
	Drone: class extends self.ISpriteInstance {},
	EMPBullet: class extends self.ISpriteInstance {},
	EMPBurst: class extends self.ISpriteInstance {},
	EMPBurst2: class extends self.ISpriteInstance {},
	EMPGrenade: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Explosion2: class extends self.ISpriteInstance {},
	FragGrenade: class extends self.ISpriteInstance {},
	GAC22Bullet: class extends self.ISpriteInstance {},
	GAR10Bullet: class extends self.ISpriteInstance {},
	GAREVMkVBullet: class extends self.ISpriteInstance {},
	GASMG20Bullet: class extends self.ISpriteInstance {},
	GATypeXVBullet: class extends self.ISpriteInstance {},
	GAVolt10: class extends self.ISpriteInstance {},
	ImpactGrenade: class extends self.ISpriteInstance {},
	Knife: class extends self.ISpriteInstance {},
	LMGBullet: class extends self.ISpriteInstance {},
	LMGTurret: class extends self.ISpriteInstance {},
	MAC11Bullet: class extends self.ISpriteInstance {},
	Mk14EBRBullet: class extends self.ISpriteInstance {},
	MKA1919Shell: class extends self.ISpriteInstance {},
	MossbergShell: class extends self.ISpriteInstance {},
	MP5Bullet: class extends self.ISpriteInstance {},
	PBPW: class extends self.ISpriteInstance {},
	PistolBullet: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	ShortyShell: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {},
	SmokeGrenade: class extends self.ISpriteInstance {},
	ToxicGrenade: class extends self.ISpriteInstance {},
	ToxicSmoke: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	BanditCharge: class extends self.ISpriteInstance {},
	BanditCharge2: class extends self.ISpriteInstance {},
	BanditCharge3: class extends self.ISpriteInstance {},
	BarbedWire: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Bomb2: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	ControlArea: class extends self.ISpriteInstance {},
	Crate: class extends self.ISpriteInstance {},
	DamageReset: class extends self.ISpriteInstance {},
	DisplayEMP: class extends self.ISpriteInstance {},
	DisplayDiffuser: class extends self.ISpriteInstance {},
	Dummy1: class extends self.ISpriteInstance {},
	Dummy2: class extends self.ISpriteInstance {},
	Dummy3: class extends self.ISpriteInstance {},
	ElectifiedBarbedWire: class extends self.ISpriteInstance {},
	ElectifiedBarbedWire2: class extends self.ISpriteInstance {},
	EMPdBandit: class extends self.ISpriteInstance {},
	EMPdBandit2: class extends self.ISpriteInstance {},
	EMPdBandit3: class extends self.ISpriteInstance {},
	HorizontalBarricadedDoor: class extends self.ISpriteInstance {},
	HorzElectricalHazard: class extends self.ISpriteInstance {},
	HorzElectricalHazard2: class extends self.ISpriteInstance {},
	HorzElectricalHazard3: class extends self.ISpriteInstance {},
	Hostage: class extends self.ISpriteInstance {},
	LargeCrate: class extends self.ISpriteInstance {},
	SoftWall: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	VertElectricalHazard: class extends self.ISpriteInstance {},
	VertElectricalHazard2: class extends self.ISpriteInstance {},
	VertElectricalHazard3: class extends self.ISpriteInstance {},
	VerticalBarricadeDoor: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LOGO: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	ScrollWheel: class extends self.ISpriteInstance {},
	DockFloor: class extends self.ISpriteInstance {},
	HorizontalBarracadedDoorIndicator: class extends self.ISpriteInstance {},
	SoftWallIndicator: class extends self.ISpriteInstance {},
	SpawnPoint: class extends self.ISpriteInstance {},
	SpawnPoints2: class extends self.ISpriteInstance {},
	SpawnPoints3: class extends self.ISpriteInstance {},
	StoneFloor: class extends self.ISpriteInstance {},
	StoneFloor10: class extends self.ISpriteInstance {},
	StoneFloor11: class extends self.ISpriteInstance {},
	StoneFloor12: class extends self.ISpriteInstance {},
	StoneFloor13: class extends self.ISpriteInstance {},
	StoneFloor14: class extends self.ISpriteInstance {},
	StoneFloor15: class extends self.ISpriteInstance {},
	StoneFloor16: class extends self.ISpriteInstance {},
	StoneFloor17: class extends self.ISpriteInstance {},
	StoneFloor2: class extends self.ISpriteInstance {},
	StoneFloor3: class extends self.ISpriteInstance {},
	StoneFloor4: class extends self.ISpriteInstance {},
	StoneFloor5: class extends self.ISpriteInstance {},
	StoneFloor6: class extends self.ISpriteInstance {},
	StoneFloor7: class extends self.ISpriteInstance {},
	StoneFloor8: class extends self.ISpriteInstance {},
	StoneFloor9: class extends self.ISpriteInstance {},
	TrainingRoomBackground: class extends self.ISpriteInstance {},
	VerticalBarricadeDoorIndicatior: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	WoodFloor2: class extends self.ISpriteInstance {},
	HUDAmmoBox: class extends self.ISpriteInstance {},
	HUDAmmoBox2: class extends self.ISpriteInstance {},
	HUDAmmoBox3: class extends self.ISpriteInstance {},
	HUDBreachingGunBullet: class extends self.ISpriteInstance {},
	HUDBullet: class extends self.ISpriteInstance {},
	HUDBullet2: class extends self.ISpriteInstance {},
	HUDC4: class extends self.ISpriteInstance {},
	HUDDroneDisplay: class extends self.ISpriteInstance {},
	HUDEMPGrenade: class extends self.ISpriteInstance {},
	HUDEMPLauncher: class extends self.ISpriteInstance {},
	HUDGrenade: class extends self.ISpriteInstance {},
	HUDHPIndicator: class extends self.ISpriteInstance {},
	HUDImpactnade: class extends self.ISpriteInstance {},
	HUDLMGBullet: class extends self.ISpriteInstance {},
	HUDPBPWDisplay: class extends self.ISpriteInstance {},
	HUDShotgunBullet: class extends self.ISpriteInstance {},
	HUDShotgunBullet2: class extends self.ISpriteInstance {},
	HUDSmokeNade: class extends self.ISpriteInstance {},
	HUDStim: class extends self.ISpriteInstance {},
	HUDToxicNade: class extends self.ISpriteInstance {},
	Important: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	EnemyBullet1: class extends self.ISpriteInstance {},
	Computer: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	ArrowLeft: class extends self.ISpriteInstance {},
	ArrowRight: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	ComputerPorts: class extends self.ISpriteInstance {},
	ComputerObject: class extends self.ISpriteInstance {},
	ComputerObject2: class extends self.ISpriteInstance {},
	ComputerObject3: class extends self.ISpriteInstance {},
	ComputerButton: class extends self.ISpriteInstance {},
	PortBlocker1: class extends self.ISpriteInstance {},
	PortBlockerText1: class extends self.ITextInstance {},
	PortBlockerText2: class extends self.ITextInstance {},
	PortBlockerText3: class extends self.ITextInstance {},
	PortBlocker2: class extends self.ISpriteInstance {},
	PortBlocker3: class extends self.ISpriteInstance {},
	ArrowLeft2: class extends self.ISpriteInstance {},
	ArrowLeft3: class extends self.ISpriteInstance {},
	ArrowLeft4: class extends self.ISpriteInstance {},
	ArrowLeft5: class extends self.ISpriteInstance {},
	ArrowLeft6: class extends self.ISpriteInstance {},
	ArrowRight2: class extends self.ISpriteInstance {},
	ArrowRight3: class extends self.ISpriteInstance {},
	ArrowRight4: class extends self.ISpriteInstance {},
	ArrowRight5: class extends self.ISpriteInstance {},
	ArrowRight6: class extends self.ISpriteInstance {},
	MoneyDisplayBackground: class extends self.ISpriteInstance {},
	TestFireBonus: class extends self.ITextInstance {},
	TestFireBonus2: class extends self.ITextInstance {},
	TestFireBonus3: class extends self.ITextInstance {},
	RelevantCollisions: class extends self.ISpriteInstance {},
	Projectiles: class extends self.ISpriteInstance {},
	Electrical: class extends self.ISpriteInstance {},
	EMPD: class extends self.ISpriteInstance {},
	Ebarbed: class extends self.ISpriteInstance {},
	PlayerBullets: class extends self.ISpriteInstance {}
}