const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.shadowlight,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.Turret,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.shadowlight.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Cnds.OnShoot
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{ShadowCaster: 0},
	{Collisions: 0},
	{Stairs: 0},
	{HP: 0},
	{SoftWall: 0},
	{AssultAmmoCount: 0},
	{ShotgunAmmoCount: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{SpawnPoints: 0},
	{ShadowLight: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Bullet: 0},
	{HorizontalBarricadedDoor: 0},
	{Turret: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{Enemy: 0},
	{Knife: 0},
	{SoftWallIndicator: 0},
	{Background: 0},
	{HorizontalBarracadedDoorIndicator: 0},
	{AltCollison: 0},
	{VerticalBarricadeDoorIndicatior: 0},
	{VerticalBarricadeDoor: 0},
	{sprites: 0},
	{Grenade: 0},
	{Explosion: 0},
	{Hostage: 0},
	{Bomb: 0},
	{Diffuser: 0},
	{ShotgunBullet: 0},
	{Enemybullet: 0},
	{TitleScreen: 0},
	{TitleText: 0},
	{Background2: 0},
	{PlayerDetection: 0},
	{Grenades: 0}
];

self.InstanceType = {
	Collisions: class extends self.ISpriteInstance {},
	Stairs: class extends self.ISpriteInstance {},
	SoftWall: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	SpawnPoints: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	HorizontalBarricadedDoor: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Knife: class extends self.ISpriteInstance {},
	SoftWallIndicator: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	HorizontalBarracadedDoorIndicator: class extends self.ISpriteInstance {},
	AltCollison: class extends self.ISpriteInstance {},
	VerticalBarricadeDoorIndicatior: class extends self.ISpriteInstance {},
	VerticalBarricadeDoor: class extends self.ISpriteInstance {},
	sprites: class extends self.ISpriteInstance {},
	Grenade: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Hostage: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Diffuser: class extends self.ISpriteInstance {},
	ShotgunBullet: class extends self.ISpriteInstance {},
	Enemybullet: class extends self.ISpriteInstance {},
	TitleScreen: class extends self.ISpriteInstance {},
	TitleText: class extends self.ITextInstance {},
	Background2: class extends self.ISpriteInstance {}
}